import Header from '@/components/header';
import Footer from '@/components/footer';
import ReduxProvider from '@/providers/ReduxProvider';
import type { Metadata } from 'next';
import { Cairo, Roboto } from 'next/font/google';
import { Locale } from '@/i18n.config';
import './globals.css';
import { Directions, Languages } from '@/components/constants/enum';
import { Toaster } from '@/components/ui/toaster';
import NextAuthSessionProvider from '@/providers/NextAuthSessionProvider';

export async function generateStaticParams() {
  return [{ locale: Languages.ARABIC }, { locale: Languages.ENGLISH }];
}

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  preload: true,
});
const cairo = Cairo({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  params,
  children,
}: {
  children: React.ReactNode;
  params: { locale: Locale };
}) {
  const locale = params.locale;
  return (
    <html
      lang={locale}
      dir={locale === Languages.ARABIC ? Directions.RTL : Directions.LTR}
    >
      <body  className={
          locale === Languages.ARABIC ? cairo.className : roboto.className
        }>
          <NextAuthSessionProvider>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
          <Toaster/>
        </ReduxProvider>
          </NextAuthSessionProvider>
      </body>
    </html>
  );
}